# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: null
        cookie_secure: true
        cookie_samesite: lax
        cookie_lifetime: 86400
        cookie_httponly: true
        name: __Host-PHPSESSID
        storage_factory_id: session.storage.factory.native

    ide: vscode

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@dev:
    framework:
        trusted_proxies: "127.0.0.1,REMOTE_ADDR"

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
