knpu_oauth2_client:
    # can be set to the service id of a service that implements Guzzle\ClientInterface
    # http_client: null

    # options to configure the default http client
    http_client_options:
        # timeout: 0
        # if you want to disable the proxy (e.g. local GitLab OAuth) - set it to "false"
        proxy: "%env(resolve:HTTP_PROXY)%"
        verify: false # ssl verification disabled

    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration

        # will create service: "knpu.oauth2.client.keycloak"
        # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\KeycloakClient
        # composer require stevenmaguire/oauth2-keycloak
        keycloak:
            type: keycloak
            client_id: "%env(resolve:IAM_CLIENT_ID)%"
            client_secret: "" # '%env(OAUTH_KEYCLOAK_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: plage_security_login_check
            # redirect_params:
            #     service: keycloak
            # Keycloak server URL
            auth_server_url: "%env(resolve:IAM_URL)%"
            # Keycloak realm
            realm: "%env(resolve:IAM_REALM)%"
            # Optional: Encryption algorith, i.e. RS256
            # encryption_algorithm: null
            # Optional: Encryption key path, i.e. ../key.pem
            # encryption_key_path: null
            # Optional: Encryption key, i.e. contents of key or certificate
            # encryption_key: null
            # whether to check OAuth2 "state": defaults to true
            use_state: true
