version: "3.4"

networks:
    web_dev:
        external: true

services:
    backend:
        build:
            context: .
            dockerfile: .docker/backend.dockerfile
            args:
                - http_proxy
                - https_proxy
                - HTTP_PROXY
                - HTTPS_PROXY
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        extra_hosts:
            - host.docker.internal:host-gateway
        # décommenter pour utilisation sans traefik
        # ports:
        #     - "9090:80"
        env_file:
            - .env.local
        networks:
            - web_dev
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.geotuileur.rule=Host(`geotuileur.docker.localhost`)"
            - "traefik.http.routers.geotuileur.entrypoints=websecure"
