version: "3.4"

networks:
    geotuileur_network:


services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            args:
                - http_proxy
                - https_proxy
                - HTTP_PROXY
                - HTTPS_PROXY
        ports:
            - "9090:8000"
        env_file:
            - .env.local
        networks:
            - geotuileur_network
        restart: unless-stopped
