version: "3"

volumes:
    db-data:

networks:
    symfony:

services:
    backend:
        build:
            context: .
            dockerfile: .docker/backend.dockerfile
            args:
                - http_proxy
                - https_proxy
                - HTTP_PROXY
                - HTTPS_PROXY
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        env_file:
            - .env.local
        networks:
            - symfony
        restart: unless-stopped
