# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    disable_delivery: false
    delivery_addresses: ["%env(MAILER_DEV_DELIVERY_ADDRESS)%"]
