monolog:
    channels:
        - mailer

    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 10

        mailer:
            type: rotating_file
            path: "%kernel.logs_dir%/mailer.log"
            channels: mailer
