# Liste de projections acceptées
# Syntaxe - <SRID>, ne prend que des codes EPSG

"EPSG:2154": "RGF93 / Lambert-93 (France métropolitaine)"
"EPSG:4326": "WGS 84"
"EPSG:2972": "RGFG95 / UTM zone 22N (Guyane)"
"EPSG:4559": "RRAF 1991 / UTM zone 20N (Antilles françaises)"
"EPSG:2975": "RGR92 / UTM zone 40S (Réunion)"
"EPSG:4471": "RGM04 / UTM zone 38S (Mayotte)"
"EPSG:4467": "RGSPM06 / UTM zone 21N (Saint-Pierre-et-Miquelon)"
"EPSG:5490": "RGAF09 / UTM zone 20N (Antilles françaises)"
